// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 647 (Captain Greenskin), 40 anchors over 583yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_647()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 647,
        {
            { -5.57f, -778.53f, 10.24f },
            { -7.92f, -758.60f, 8.66f },
            { -4.70f, -778.49f, 9.77f },
            { -19.68f, -792.46f, 17.92f },
            { -21.33f, -796.27f, 12.66f },
            { -26.13f, -789.33f, 11.36f },
            { -21.33f, -796.27f, 12.66f },
            { -39.49f, -789.79f, 19.41f },
            { -56.08f, -784.09f, 18.71f },
            { -45.02f, -784.97f, 19.26f },
            { -68.62f, -785.08f, 6.10f },
            { -84.51f, -786.12f, 1.86f },
            { -91.45f, -786.58f, 17.16f },
            { -67.37f, -786.31f, 17.49f },
            { -48.07f, -786.50f, 12.61f },
            { -33.87f, -792.71f, 16.22f },
            { -28.02f, -795.31f, 4.89f },
            { -10.97f, -786.01f, 13.20f },
            { -12.14f, -777.24f, 4.86f },
            { -12.78f, -788.42f, 14.46f },
            { -27.31f, -796.58f, 12.93f },
            { -41.00f, -790.12f, 16.93f },
            { -59.41f, -786.21f, -0.49f },
            { -78.42f, -786.71f, 5.06f },
            { -97.45f, -787.22f, 0.34f },
            { -122.73f, -786.57f, 17.46f },
            { -121.23f, -794.94f, 17.74f },
            { -121.37f, -787.79f, 17.96f },
            { -90.02f, -779.54f, 25.32f },
            { -85.22f, -778.64f, 26.74f },
            { -106.43f, -793.29f, 28.16f },
            { -97.74f, -799.36f, 30.91f },
            { -88.23f, -799.26f, 35.58f },
            { -93.45f, -799.37f, 34.59f },
            { -78.17f, -797.46f, 38.45f },
            { -59.72f, -793.28f, 39.63f },
            { -42.74f, -795.35f, 39.96f },
            { -49.85f, -805.35f, 43.13f },
            { -45.30f, -798.79f, 40.29f },
            { -56.26f, -792.37f, 39.57f },
        });
}
