// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 62530 (Velthelaxx the Defiler), 37 anchors over 599yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_62530()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 62530,
        {
            { -422.25f, 28.57f, -47.70f },
            { -429.95f, 21.06f, -48.12f },
            { -445.67f, 16.16f, -48.92f },
            { -460.70f, 8.50f, -47.86f },
            { -475.74f, 1.98f, -47.42f },
            { -493.51f, -7.00f, -46.19f },
            { -509.81f, -16.17f, -44.68f },
            { -521.42f, -31.29f, -40.44f },
            { -538.47f, -40.94f, -39.52f },
            { -555.00f, -42.49f, -37.91f },
            { -573.32f, -43.06f, -34.66f },
            { -589.58f, -39.49f, -30.51f },
            { -598.93f, -36.90f, -27.43f },
            { -615.55f, -36.42f, -23.57f },
            { -620.81f, -28.52f, -22.50f },
            { -639.62f, -24.38f, -18.77f },
            { -657.41f, -14.71f, -18.22f },
            { -666.91f, 1.68f, -22.62f },
            { -675.97f, 11.98f, -26.38f },
            { -694.49f, 26.89f, -30.43f },
            { -712.35f, 31.03f, -30.37f },
            { -721.79f, 17.46f, -28.81f },
            { -721.73f, -0.39f, -33.04f },
            { -716.80f, -17.28f, -35.84f },
            { -713.12f, -25.23f, -36.81f },
            { -703.95f, -28.92f, -33.35f },
            { -684.44f, -31.53f, -30.17f },
            { -668.62f, -34.54f, -30.11f },
            { -661.10f, -38.02f, -29.55f },
            { -655.88f, -57.27f, -29.18f },
            { -654.35f, -69.21f, -29.34f },
            { -638.73f, -77.15f, -30.01f },
            { -629.90f, -94.56f, -28.09f },
            { -628.18f, -111.02f, -28.88f },
            { -625.07f, -127.17f, -28.72f },
            { -619.90f, -150.18f, -27.50f },
            { -616.39f, -169.79f, -28.27f },
        });
}
