// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 61965 (Vangros), 40 anchors over 679yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_61965()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 61965,
        {
            { -272.17f, -307.12f, -68.26f },
            { -264.98f, -292.30f, -67.07f },
            { -257.35f, -277.26f, -65.29f },
            { -266.02f, -259.72f, -63.11f },
            { -274.27f, -241.02f, -60.84f },
            { -275.41f, -222.94f, -63.48f },
            { -274.45f, -206.24f, -62.55f },
            { -283.27f, -191.44f, -62.49f },
            { -298.09f, -177.28f, -62.04f },
            { -305.69f, -161.34f, -60.15f },
            { -320.75f, -154.89f, -61.05f },
            { -334.71f, -146.42f, -62.24f },
            { -343.98f, -131.13f, -63.08f },
            { -351.19f, -116.49f, -63.85f },
            { -369.09f, -105.25f, -64.89f },
            { -380.43f, -85.35f, -65.33f },
            { -387.78f, -66.88f, -65.16f },
            { -397.99f, -52.75f, -65.26f },
            { -403.40f, -46.21f, -65.34f },
            { -399.55f, -38.79f, -65.15f },
            { -411.38f, -26.52f, -65.35f },
            { -419.42f, -11.97f, -65.38f },
            { -437.53f, -4.70f, -65.21f },
            { -454.41f, -5.26f, -66.11f },
            { -474.34f, -12.05f, -66.90f },
            { -488.52f, -22.88f, -67.70f },
            { -495.42f, -26.99f, -67.88f },
            { -500.73f, -46.95f, -67.40f },
            { -508.27f, -62.69f, -67.44f },
            { -512.81f, -78.41f, -66.72f },
            { -516.33f, -96.08f, -67.19f },
            { -517.11f, -115.15f, -70.07f },
            { -511.52f, -132.96f, -67.85f },
            { -500.22f, -145.89f, -66.41f },
            { -490.31f, -164.49f, -65.85f },
            { -487.43f, -172.78f, -65.55f },
            { -470.90f, -180.54f, -64.67f },
            { -451.62f, -192.07f, -64.71f },
            { -438.60f, -202.63f, -65.55f },
            { -423.57f, -214.80f, -65.64f },
        });
}
