// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3653 (Kresh), 6 anchors over 74yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3653()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3653,
        {
            { -43.68f, 251.98f, -92.34f },
            { -33.44f, 238.08f, -93.38f },
            { -27.30f, 221.01f, -96.44f },
            { -18.95f, 221.50f, -102.14f },
            { -9.16f, 227.70f, -106.18f },
            { -11.18f, 247.04f, -105.83f },
        });
}
