// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 34 anchors over 619yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -41.55f, 301.73f, -106.42f },
            { -53.53f, 312.15f, -106.42f },
            { -60.58f, 317.24f, -106.68f },
            { -63.49f, 336.09f, -106.36f },
            { -65.86f, 353.00f, -106.05f },
            { -64.70f, 370.28f, -104.90f },
            { -62.51f, 385.66f, -105.80f },
            { -59.34f, 406.17f, -106.25f },
            { -50.71f, 423.85f, -105.08f },
            { -38.21f, 438.33f, -103.02f },
            { -9.25f, 462.33f, -92.47f },
            { 1.75f, 461.98f, -84.83f },
            { 4.06f, 458.46f, -78.38f },
            { -0.05f, 435.68f, -70.58f },
            { -2.18f, 427.03f, -67.72f },
            { 3.19f, 414.46f, -63.93f },
            { 26.13f, 402.10f, -59.75f },
            { 36.83f, 401.39f, -60.06f },
            { 55.58f, 430.34f, -63.23f },
            { 52.66f, 447.82f, -64.07f },
            { 48.06f, 465.46f, -65.20f },
            { 46.59f, 475.33f, -65.53f },
            { 32.95f, 486.08f, -64.05f },
            { 23.91f, 501.13f, -60.01f },
            { 13.78f, 504.85f, -58.56f },
            { -16.24f, 494.43f, -55.31f },
            { -18.41f, 484.72f, -55.92f },
            { -49.52f, 476.12f, -55.97f },
            { -68.01f, 475.14f, -62.81f },
            { -77.16f, 469.29f, -66.37f },
            { -86.29f, 461.59f, -69.47f },
            { -101.17f, 441.24f, -73.05f },
            { -128.35f, 415.40f, -72.75f },
            { -155.04f, 415.49f, -72.06f },
        });
}
