// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4830 (Old Serra'kis), 26 anchors over 407yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4830()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4830,
        {
            { -614.14f, -188.89f, -27.64f },
            { -618.62f, -172.32f, -28.21f },
            { -619.88f, -153.62f, -28.24f },
            { -624.60f, -137.98f, -28.21f },
            { -627.35f, -121.86f, -28.97f },
            { -628.21f, -105.51f, -28.20f },
            { -630.54f, -87.45f, -28.84f },
            { -632.69f, -79.62f, -29.97f },
            { -647.64f, -72.87f, -29.70f },
            { -655.39f, -57.10f, -29.68f },
            { -661.86f, -40.78f, -29.95f },
            { -679.11f, -31.87f, -30.26f },
            { -696.36f, -32.91f, -30.03f },
            { -713.82f, -34.43f, -30.03f },
            { -715.42f, -50.58f, -30.03f },
            { -715.76f, -67.90f, -30.03f },
            { -716.31f, -84.31f, -30.03f },
            { -721.60f, -103.69f, -30.04f },
            { -738.33f, -107.27f, -30.09f },
            { -746.91f, -110.99f, -34.00f },
            { -755.14f, -110.44f, -38.29f },
            { -770.27f, -101.94f, -39.61f },
            { -787.42f, -101.00f, -37.69f },
            { -796.17f, -119.63f, -35.59f },
            { -795.93f, -138.44f, -38.21f },
            { -789.89f, -148.54f, -41.18f },
        });
}
