// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3671 (Lady Anacondra), 15 anchors over 189yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3671()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3671,
        {
            { -163.49f, 132.90f, -73.66f },
            { -146.33f, 135.92f, -73.31f },
            { -130.18f, 142.48f, -76.00f },
            { -121.94f, 157.68f, -76.18f },
            { -110.56f, 170.49f, -79.24f },
            { -99.91f, 183.30f, -78.42f },
            { -91.05f, 190.15f, -82.35f },
            { -87.04f, 190.44f, -86.88f },
            { -82.62f, 206.11f, -93.23f },
            { -79.92f, 213.95f, -93.99f },
            { -63.58f, 216.34f, -93.30f },
            { -52.12f, 215.90f, -94.62f },
            { -39.47f, 230.35f, -93.69f },
            { -37.68f, 238.23f, -92.95f },
            { -41.45f, 246.00f, -93.17f },
        });
}
