// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 1763 (Gilnid), 27 anchors over 421yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_1763()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 1763,
        {
            { -270.52f, -487.84f, 50.03f },
            { -283.58f, -501.62f, 49.67f },
            { -287.84f, -524.22f, 50.34f },
            { -285.60f, -554.46f, 49.23f },
            { -296.19f, -565.26f, 49.39f },
            { -301.10f, -582.29f, 48.20f },
            { -292.97f, -563.77f, 48.73f },
            { -292.62f, -553.18f, 49.49f },
            { -288.99f, -569.60f, 49.79f },
            { -300.48f, -583.49f, 48.82f },
            { -292.77f, -608.24f, 47.62f },
            { -280.44f, -592.80f, 50.42f },
            { -278.40f, -576.93f, 52.91f },
            { -269.65f, -573.29f, 51.12f },
            { -263.21f, -582.76f, 50.72f },
            { -244.98f, -581.59f, 38.24f },
            { -228.62f, -587.73f, 20.96f },
            { -209.71f, -585.77f, 21.56f },
            { -191.96f, -581.84f, 20.93f },
            { -183.62f, -564.02f, 19.93f },
            { -187.92f, -562.89f, 19.95f },
            { -189.58f, -570.78f, 21.63f },
            { -191.63f, -560.65f, 19.96f },
            { -208.54f, -573.18f, 21.85f },
            { -200.41f, -570.55f, 21.59f },
            { -198.44f, -575.22f, 21.56f },
            { -200.83f, -556.96f, 20.40f },
        });
}
