// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 40 anchors over 616yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -61.27f, 316.95f, -107.92f },
            { -73.64f, 332.48f, -106.19f },
            { -69.29f, 351.82f, -106.16f },
            { -62.77f, 369.37f, -104.96f },
            { -61.63f, 387.63f, -105.71f },
            { -62.42f, 407.90f, -106.56f },
            { -53.10f, 424.19f, -105.53f },
            { -42.33f, 437.53f, -104.86f },
            { -29.75f, 448.23f, -101.83f },
            { -16.53f, 460.22f, -96.92f },
            { -10.66f, 466.50f, -94.35f },
            { -3.22f, 463.78f, -88.96f },
            { 4.72f, 464.67f, -84.08f },
            { 5.77f, 460.58f, -79.89f },
            { 2.54f, 448.79f, -75.66f },
            { -0.99f, 431.50f, -69.37f },
            { -3.63f, 415.36f, -65.74f },
            { -7.12f, 407.73f, -62.52f },
            { 17.23f, 405.49f, -59.60f },
            { 32.49f, 402.73f, -60.81f },
            { 45.32f, 412.48f, -63.33f },
            { 59.16f, 429.02f, -64.65f },
            { 63.18f, 436.52f, -64.52f },
            { 50.92f, 447.73f, -65.33f },
            { 44.73f, 463.41f, -65.85f },
            { 44.07f, 471.83f, -65.28f },
            { 28.08f, 485.84f, -64.05f },
            { 27.91f, 493.94f, -62.38f },
            { 6.60f, 494.59f, -57.88f },
            { -11.45f, 495.85f, -55.75f },
            { -22.51f, 482.66f, -55.09f },
            { -44.11f, 478.85f, -55.45f },
            { -63.93f, 474.44f, -60.74f },
            { -72.12f, 471.38f, -64.83f },
            { -90.08f, 462.32f, -69.97f },
            { -97.57f, 445.65f, -73.33f },
            { -107.44f, 429.47f, -73.28f },
            { -123.29f, 419.19f, -72.38f },
            { -140.27f, 417.81f, -72.09f },
            { -147.46f, 414.28f, -72.09f },
        });
}
