// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 646 (Mr. Smite), 37 anchors over 616yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_646()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 646,
        {
            { -80.41f, -572.27f, 51.87f },
            { -102.31f, -577.89f, 51.23f },
            { -119.74f, -573.03f, 51.68f },
            { -138.16f, -577.10f, 19.44f },
            { -162.62f, -579.49f, 19.30f },
            { -187.47f, -582.26f, 20.94f },
            { -211.30f, -590.07f, 21.06f },
            { -188.18f, -582.73f, 20.26f },
            { -167.65f, -580.37f, 19.38f },
            { -141.49f, -588.05f, 19.17f },
            { -131.21f, -605.36f, 15.69f },
            { -125.38f, -628.63f, 14.18f },
            { -113.15f, -648.29f, 8.73f },
            { -101.66f, -667.56f, 7.49f },
            { -85.19f, -679.57f, 2.99f },
            { -77.54f, -700.41f, -3.18f },
            { -79.83f, -695.15f, 0.34f },
            { -84.91f, -680.04f, 3.46f },
            { -100.96f, -684.48f, 8.13f },
            { -101.99f, -691.95f, 8.97f },
            { -110.01f, -697.45f, 6.33f },
            { -106.18f, -685.64f, 7.87f },
            { -111.78f, -683.04f, 4.58f },
            { -89.70f, -680.11f, 7.26f },
            { -82.65f, -685.63f, 1.06f },
            { -77.11f, -701.36f, -3.69f },
            { -68.51f, -720.63f, -11.05f },
            { -58.61f, -740.35f, -9.05f },
            { -43.30f, -757.89f, -12.30f },
            { -26.53f, -764.55f, -3.84f },
            { -12.34f, -759.74f, 4.84f },
            { -11.43f, -753.41f, 9.22f },
            { -4.29f, -753.57f, 9.44f },
            { -4.30f, -771.26f, 9.40f },
            { -1.93f, -776.80f, 10.23f },
            { -5.41f, -769.16f, 9.73f },
            { -1.69f, -779.36f, 10.46f },
        });
}
