// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 645 (Cookie), 25 anchors over 377yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_645()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 645,
        {
            { -3.02f, -766.15f, 9.74f },
            { -22.25f, -740.90f, 9.00f },
            { -34.26f, -731.72f, 8.72f },
            { -16.32f, -745.86f, 9.48f },
            { -5.94f, -763.96f, 8.73f },
            { -6.23f, -782.83f, 10.75f },
            { -23.47f, -796.09f, 15.16f },
            { -26.13f, -789.33f, 11.36f },
            { -19.37f, -798.93f, 12.71f },
            { -26.31f, -790.99f, 12.02f },
            { -21.00f, -786.33f, 11.53f },
            { -23.55f, -793.31f, 12.55f },
            { -27.33f, -790.24f, 12.46f },
            { -44.30f, -811.20f, 27.49f },
            { -55.56f, -825.11f, 37.46f },
            { -76.53f, -813.33f, -14.14f },
            { -71.49f, -813.11f, -8.35f },
            { -76.43f, -824.71f, -9.93f },
            { -70.38f, -830.58f, -9.37f },
            { -70.78f, -859.37f, -2.02f },
            { -64.65f, -884.11f, 7.57f },
            { -65.64f, -889.48f, 14.21f },
            { -67.36f, -871.83f, 16.09f },
            { -67.81f, -856.37f, 17.09f },
            { -77.45f, -855.43f, 17.61f },
        });
}
