// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4887 (Ghamoo-ra), 23 anchors over 365yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4887()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4887,
        {
            { -151.89f, 106.96f, -39.87f },
            { -149.53f, 89.16f, -42.57f },
            { -160.52f, 75.74f, -47.60f },
            { -167.72f, 66.01f, -46.35f },
            { -185.21f, 58.54f, -50.32f },
            { -199.30f, 49.35f, -52.69f },
            { -214.48f, 41.82f, -52.75f },
            { -236.27f, 41.21f, -53.87f },
            { -255.74f, 50.49f, -55.41f },
            { -270.30f, 58.68f, -58.08f },
            { -288.08f, 66.87f, -63.50f },
            { -304.63f, 66.71f, -64.09f },
            { -321.29f, 70.67f, -62.23f },
            { -328.55f, 85.55f, -59.37f },
            { -323.80f, 101.41f, -57.68f },
            { -322.61f, 109.72f, -53.76f },
            { -322.04f, 119.61f, -49.87f },
            { -338.82f, 130.49f, -49.72f },
            { -353.98f, 138.52f, -50.33f },
            { -371.36f, 149.06f, -51.34f },
            { -381.16f, 162.38f, -56.12f },
            { -386.67f, 179.22f, -57.11f },
            { -394.18f, 183.61f, -56.48f },
        });
}
