// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 5775 (Verdan the Everliving), 4 anchors over 43yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_5775()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 5775,
        {
            { -102.90f, -15.43f, -27.52f },
            { -111.02f, -13.28f, -28.36f },
            { -102.01f, 1.83f, -29.92f },
            { -90.51f, 15.27f, -30.95f },
        });
}
