// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 14 anchors over 192yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -201.22f, -452.86f, 55.12f },
            { -189.33f, -463.85f, 54.30f },
            { -183.92f, -483.99f, 54.05f },
            { -194.19f, -502.70f, 53.61f },
            { -189.79f, -497.33f, 53.86f },
            { -202.25f, -508.57f, 52.52f },
            { -218.35f, -501.95f, 50.58f },
            { -219.47f, -494.27f, 50.19f },
            { -228.60f, -490.93f, 48.80f },
            { -230.87f, -483.60f, 48.92f },
            { -251.59f, -487.62f, 49.49f },
            { -272.83f, -489.15f, 49.45f },
            { -288.42f, -502.90f, 50.03f },
            { -284.99f, -499.88f, 49.99f },
        });
}
