// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 6243 (Gelihast), 42 anchors over 681yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_6243()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 6243,
        {
            { -329.05f, 307.36f, -58.90f },
            { -337.53f, 302.81f, -64.40f },
            { -343.62f, 297.52f, -68.55f },
            { -354.42f, 289.28f, -75.71f },
            { -366.22f, 275.97f, -77.65f },
            { -375.30f, 262.29f, -72.85f },
            { -381.17f, 256.01f, -69.12f },
            { -397.55f, 253.26f, -64.75f },
            { -413.78f, 251.69f, -59.45f },
            { -429.21f, 245.40f, -54.15f },
            { -445.80f, 238.89f, -53.80f },
            { -454.21f, 238.00f, -53.89f },
            { -461.83f, 230.39f, -53.53f },
            { -468.91f, 234.78f, -54.05f },
            { -484.23f, 225.11f, -55.67f },
            { -496.72f, 214.07f, -59.72f },
            { -515.62f, 211.21f, -62.92f },
            { -533.46f, 208.21f, -62.51f },
            { -553.13f, 213.26f, -60.24f },
            { -571.59f, 214.84f, -54.32f },
            { -587.18f, 220.62f, -51.62f },
            { -605.28f, 222.59f, -50.31f },
            { -611.60f, 216.89f, -50.09f },
            { -609.84f, 196.87f, -50.76f },
            { -608.42f, 178.80f, -53.87f },
            { -613.50f, 163.58f, -56.18f },
            { -622.01f, 145.25f, -57.34f },
            { -626.86f, 138.18f, -57.59f },
            { -626.55f, 117.44f, -56.58f },
            { -626.56f, 100.54f, -56.59f },
            { -621.64f, 78.55f, -55.73f },
            { -605.59f, 57.01f, -55.36f },
            { -595.22f, 43.36f, -52.79f },
            { -584.83f, 28.60f, -49.59f },
            { -574.25f, 10.61f, -48.16f },
            { -556.97f, 8.19f, -45.37f },
            { -539.57f, 3.67f, -42.06f },
            { -520.50f, -0.66f, -42.77f },
            { -497.52f, -1.41f, -45.59f },
            { -479.82f, 3.34f, -47.33f },
            { -462.49f, 11.20f, -47.79f },
            { -447.29f, 19.28f, -48.05f },
        });
}
