// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4831 (Lady Sarevess), 15 anchors over 172yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4831()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4831,
        {
            { -432.56f, 203.53f, -52.76f },
            { -425.27f, 218.79f, -52.98f },
            { -415.65f, 233.62f, -54.11f },
            { -398.43f, 242.39f, -60.58f },
            { -388.18f, 247.60f, -65.31f },
            { -383.27f, 257.75f, -69.39f },
            { -380.95f, 265.87f, -72.50f },
            { -375.84f, 275.52f, -75.99f },
            { -360.74f, 283.43f, -78.16f },
            { -356.21f, 299.09f, -74.16f },
            { -348.35f, 304.07f, -69.79f },
            { -341.96f, 309.13f, -64.50f },
            { -337.26f, 315.76f, -61.20f },
            { -334.25f, 323.63f, -58.58f },
            { -340.15f, 330.85f, -56.13f },
        });
}
