// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 26 anchors over 354yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -17.01f, -382.77f, 61.68f },
            { -37.86f, -372.32f, 57.09f },
            { -41.99f, -371.35f, 56.86f },
            { -51.67f, -377.94f, 55.48f },
            { -57.25f, -365.10f, 56.16f },
            { -49.78f, -376.81f, 55.70f },
            { -53.06f, -386.29f, 55.16f },
            { -50.16f, -380.24f, 55.80f },
            { -74.79f, -381.12f, 55.33f },
            { -79.07f, -382.14f, 55.31f },
            { -78.55f, -377.75f, 55.63f },
            { -98.25f, -373.49f, 58.67f },
            { -100.56f, -385.84f, 58.18f },
            { -96.65f, -377.30f, 58.87f },
            { -118.53f, -382.96f, 58.71f },
            { -128.01f, -384.63f, 59.76f },
            { -122.10f, -397.90f, 58.60f },
            { -124.37f, -406.80f, 59.07f },
            { -134.70f, -415.66f, 57.75f },
            { -133.64f, -401.08f, 58.59f },
            { -152.63f, -396.31f, 56.82f },
            { -179.62f, -409.47f, 55.72f },
            { -185.33f, -424.52f, 54.56f },
            { -190.80f, -444.30f, 54.43f },
            { -183.33f, -449.24f, 55.29f },
            { -198.98f, -452.32f, 55.27f },
        });
}
